name: Levelcraft

main: me.samkio.levelcraft.Levelcraft
version: 2.3
description: >
             Commands for use with the Levelcraft experience-based plugin for Minecraft.

commands:
  level:
    description: Returns information about a player's experience and levels.
    usage:
  lvl:
    description: Returns information about a player's experience and levels.
    usage: